branch-defaults:
  master:
    environment: status-board-example-prod
global:
  application_name: status-board-example-prod
  default_platform: 64bit Amazon Linux 2017.09 v4.4.5 running Node.js
  default_region: us-east-1
  sc: git